#+STARTUP: content hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)

* Архив задач

** DONE Сделать настройку и запись пустой директории
   CLOSED: [2017-05-09 Вт 10:37]
   :PROPERTIES:
   :issue_id: 1
   :issue_type: task
   :ARCHIVE_TIME: 2017-05-09 Вт 10:39
   :ARCHIVE_FILE: ~/prog/projects/c/kronhi/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

** DONE Переделать запись пустой директории
   CLOSED: [2017-06-01 Чт 11:39]
   :PROPERTIES:
   :issue_id: 12
   :issue_type: task
   :ARCHIVE_TIME: 2017-06-01 Чт 11:40
   :ARCHIVE_FILE: ~/prog/projects/c/kronhi/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2017-05-27 Сб]

   Сейчас для записи директории используется структура с выделением
   памяти, методом создания непрерывного заголовка и его непрерывной
   записью в назначение. Нужно сделать такую систему, где поля
   заголовка могут быть несмежными, могут писаться по отдельности и
   между полями могут понадобиться ещё какие-то операции. Выделение
   памяти тоже нужно убрать, оставив только группировку имён в
   структуре.

   [2017-05-30 Вт]

   Пришлось сохранить некоторое выделение памяти. Под саму структуру
   память не выделяется, а под её поля выделяется, так как иначе их
   надо держать снаружи.

** DONE Сделать добавление файла в пустую директорию
   CLOSED: [2017-06-26 Пн 19:43]
   :PROPERTIES:
   :issue_id: 9
   :issue_type: task
   :ARCHIVE_TIME: 2017-06-26 Пн 19:45
   :ARCHIVE_FILE: ~/prog/projects/c/kronhi/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

** DONE Сделать структуру каталога и файлов в нём для записи
   CLOSED: [2017-07-05 Ср 07:18]
   :PROPERTIES:
   :issue_id: 7
   :issue_type: task
   :ARCHIVE_TIME: 2017-07-05 Ср 07:21
   :ARCHIVE_FILE: ~/prog/projects/c/kronhi/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2017-05-09 Вт]

   Должны быть операции записи и добавления. При записи должен
   создаваться каталог, следом должен идти файл или очередь
   файлов. Сам каталог хранит описание своего хранилища и количество
   файлов в нём. Сами файлы хранят свои имена, свои контрольные суммы
   содержимого. При записи файла он должен читаться обратно с
   проверкой контрольной суммы. При добавлении нужно сохранять адрес
   каталога, чтобы после добавления увеличить число файлов в
   каталоге. При сбое записи файла число файлов в каталоге должно
   остаться прежним.

* Архив багов

** FIXED Увеличить offset для перемещения по большим файлам
   CLOSED: [2017-05-11 Чт 20:38]
   :PROPERTIES:
   :issue_id: 2
   :issue_type: bug
   :ARCHIVE_TIME: 2017-05-11 Чт 20:40
   :ARCHIVE_FILE: ~/prog/projects/c/kronhi/tasks/tasks.org
   :ARCHIVE_OLPATH: Баги
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: FIXED
   :END:

   [2017-05-09 Вт]

   На данный момент для offset'а используется size_t, что ограничивает
   его размером 4Gb.
   Нужно использовать либо тип double либо тип с длинной арифметикой с
   набором методов. Так как тип double не являяется нативным типом для
   этого, лучше использовать тип с длинной арифметикой.
   Так же тип с длинной арифметикой нужно соединить с вводом/выводом в
   оболочке.

   [2017-05-11 Чт]

   Построил абстрактное большое число и реализовал его через
   double. Теперь по offset'у редактируется файл около 9000Tb, хотя
   поведение fopen() на таком большом файле неизвестно. Настоящая
   длинная арифметика вызвала проблемы с преобразованием из строки
   (слишком сложно всё, нужны юнит-тесты).

   Теперь требуется опитимизация посимвольной промотки offset'а при
   записи, так как промотка offset'а занимает много времени (секунды
   на мегабайты и минуты на гигабайты).


* Архив окружения

** DONE Добавить в Makefile отладочную команду
   CLOSED: [2017-05-12 Пт 12:53]
   :PROPERTIES:
   :issue_id: 3
   :issue_type: task
   :ARCHIVE_TIME: 2017-05-12 Пт 12:54
   :ARCHIVE_FILE: ~/prog/projects/c/kronhi/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2017-05-09 Вт]

   Так как часто надо посмотреть внутренности при выполнении
   программы, нужно сделать команду (или набор команд) для отладочной
   компиляции и отладочного запуска. В результате должна стать
   доступна удобная отладка из gdb.

** DONE Добавить в Makefile тестировочную команду
   CLOSED: [2017-05-13 Сб 20:36]
   :PROPERTIES:
   :issue_id: 4
   :issue_type: task
   :ARCHIVE_TIME: 2017-05-13 Сб 20:38
   :ARCHIVE_FILE: ~/prog/projects/c/kronhi/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2017-05-09 Вт]

   Иногда надо по-быстрому обложить что-то тестами, когда точно не
   знаешь, как оно работает. Поэтому нужна инфраструктура, в которую
   можно быстро добавлять тесты и которые потом можно быстро
   скомпилировать и быстро запустить.
